---
# tasks file for jby-profile
#
# install jbyconfig repo in home/<target-user>
- name: Clone jbyconfig repo to target user
  become_user: "{{ target_username }}"
  git:
    repo: https://github.com/byates/jbyconfig.git
    dest: "/home/{{ target_username }}/jbyconfig"
    version: master
    update: yes
  # This is a hack to handle the case where there is already a repo which already
  # has remotes. When this is the case, this module fails.
  failed_when: false

# add code to source jby-profile form .bashrc
- name: add code to source jby-profile form .bashrc
  become_user: "{{ target_username }}"
  lineinfile:
    path: "/home/{{ target_username }}/.bashrc"
    line: if [ -f ~/jbyconfig/jby_bashrc.sh ]; then . ~/jbyconfig/jby_bashrc.sh; fi

