---

- name: Install repository
  become: yes
  yum_repository:
    name: carlwgeorge-ripgrep
    description: "Copr repo for ripgrep owned by carlwgeorge"
    baseurl: "https://copr-be.cloud.fedoraproject.org/results/carlwgeorge/ripgrep/epel-7-$basearch/"
    gpgkey: "https://copr-be.cloud.fedoraproject.org/results/carlwgeorge/ripgrep/pubkey.gpg"

- name: Install package
  become: yes
  yum:
    name: ripgrep
