---
galaxy_info:
  author: "Brent Yates"
  description: "Ansible role that installs Scala SBT"
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
  galaxy_tags:
    - development
dependencies: []
