---
# tasks file for create-user
#
- name: Create groups and user account
  block:
    - name: Ensure requested groups exists
      group:
        name: "{{ item }}"
        state: present
      loop: "{{ user_groups }}"

    - name: Add the user
      user:
        name: "{{ target_username }}"
        state: present
        shell: /bin/bash
        createhome: yes
        groups: "{{ user_groups | join(',') }}"
        append: yes
        password: "{{ user_pass }}"

    - name: Set authorized key taken from file
      authorized_key:
        user: "{{ target_username }}"
        state: present
        key: "{{ lookup('file', user_keyfile) }}"

  when: inventory_hostname != "127.0.0.1"

