---

- name: ubuntu package udpate
  apt:
    upgrade: 'yes'
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Yum package update
  yum:
    name: '*'
    state: latest
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: DNF package update
  dnf:
    name: '*'
    state: latest
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8'

