galaxy_info:
  author: Brent Yates
  description: Adds include directive in user .gitconfig to point to repo config
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - bionic
    - name: CentOS
      versions:
        - 7
        - 8
  galaxy_tags:
    - development

dependencies: []

