---
# tasks file for ansible-svlint
#
- name: "svlint | Get $HOME"
  command: "echo $HOME"
  register: shell_home_dir
  changed_when: false

- name: "svlint | Download and extract the binary files"
  unarchive:
    src: "https://github.com/dalance/svlint/releases/download/v{{ svlint_git_tag }}/svlint-v{{ svlint_git_tag }}-x86_64-lnx.zip"
    dest: "{{ svlint_install_prefix }}"
    remote_src: yes

