---

# install jbyconfig repo in home/target_username
- name: Clone jbyconfig repo to user home directory
  become_user: "{{ target_username }}"
  git:
    repo: https://github.com/byates/jbyconfig.git
    dest: "/home/{{ target_username }}/jbyconfig"
    version: master
    update: yes
  # This is a hack to handle the case where there is already a repo which already
  # has remotes. When this is the case, this module fails.
  failed_when: false

- name: Create the nvim config directory for target_username user
  become_user: "{{ target_username }}"
  file:
    path: "/home/{{ target_username }}/.config/nvim"
    state: directory
    mode: '0755'

- name: Create symbolic links to nvim config files
  become_user: "{{ target_username }}"
  become: yes
  file:
    src: "/home/{{ target_username }}/jbyconfig/nvim/{{ item.path }}"
    dest: "/home/{{ target_username }}/.config/nvim/{{ item.path }}"
    state: link
  with_items:
    - { path: 'init.vim' }
    - { path: 'vim_go_init.vim' }
    - { path: 'vim_ui_init.vim' }
    - { path: 'vim_cpp_init.vim' }
    - { path: 'vim_keys_init.vim' }
    - { path: 'vim_python_init.vim' }
    - { path: 'vim_editing_init.vim' }
    - { path: 'vim_plugins_init.vim' }
    - { path: 'vim_ansible.vim' }
    - { path: 'coc-settings.json' }


