---
# tasks file for ansible-bat
#
- name: Download and extract the binary files
  unarchive:
    src: "https://github.com/sharkdp/bat/releases/download/v{{ bat_version }}/bat-v{{ bat_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest: /tmp
    remote_src: yes
  changed_when: false

- name: Copy the bat exectuable to /usr/bin
  copy:
    remote_src: yes
    src: "/tmp/bat-v{{ bat_version }}-x86_64-unknown-linux-musl/bat"
    dest: "{{ bat_dest }}/bat"
    owner: root
    group: root
    mode: '0755'
  changed_when: true

- name: Delete the temp directory now that we've got what we want.
  file:
    path: "/tmp/bat-v{{ bat_version }}-x86_64-unknown-linux-musl"
    state: absent
  changed_when: false

- name: Clone bat extras repo
  git:
    repo: https://github.com/eth-p/bat-extras.git
    dest: /tmp/bat-extras
    version: master
  changed_when: false

- name: Run build on bat extras
  command: /tmp/bat-extras/build.sh --install --prefix=/usr --minify=none
  failed_when: false
  changed_when: true

- name: Delete the temp directory now that we've got what we want.
  file:
    path: "/tmp/bat-extras"
    state: absent
  changed_when: false

