---

- include_tasks: "{{ lookup('first_found', install_file) }}"
  vars:
    install_file:
      - "{{ ansible_distribution|replace(' ', '_') | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
      - "{{ ansible_distribution|replace(' ', '_') | lower }}.yml"
      - "{{ ansible_os_family | lower  }}.yml"
      - "default.yml"


